### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by MilorES**
Fix indentation "services".

### CODE REVIEW

**Comment by MilorES** [comment]
@tiredofit Won't you take a look?

**Comment by jaydio** [comment]
@tiredofit Can you merge this in? Was about to send the same PR :)

**Comment by tiredofit** [comment]
It says `nano` in front of services - Going to close this and will fix from my side..

**Comment by MilorES** [comment]
Sorry for the inconvenience, thanks for fixing it.

See if you can check out #39 as it's needed for backups to work!

**Pull request closed without merging**
